version: '2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db 
    environment:
      PGUSER: bitcointousdapp
      PGHOST: db
      PGPASSWORD: bitcointousdpass
      PGDATABASE: bitcointousd
      PGPORT: 5432
  cron:
    build: .
    command: npm run cron
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - db 
    environment:
      PGUSER: bitcointousdapp
      PGHOST: db
      PGPASSWORD: bitcointousdpass
      PGDATABASE: bitcointousd
      PGPORT: 5432
  db:
    image: timescale/timescaledb:latest-pg11
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: bitcointousdapp
      POSTGRES_PASSWORD: bitcointousdpass
      POSTGRES_DB: bitcointousd
